config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
    resources :profiles
    resources :users, only: [:index, :destroy, :show] do
      get 'details'
      get 'lock_user'
    end
    resources :payments
    post 'admin_payment' => 'payments#admin_payment'

    resources :notifications, only: [:index, :destroy]
    resources :configurable, only: [:edit, :update]
    post 'seen_notifications' => 'notifications#seen_notifications'
    post 'change_password' => 'users#change_password'
    post 'calculate_price' => 'posts#calculate_price'
    resources :bids
    resources :posts do
      get 'my_post_details'
    end
    get 'my_post_false' => 'posts#my_post_false'
    get 'my_post_true' => 'posts#my_post_true'
    get 'my_bid' => 'bids#my_bid'

    resources :shippers
    resources :reviews, only: [:index, :create]
    resources :reports, only: [:create, :destroy]
    resources :warning, only: :index


 root :to => 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.is_admin
      can :manage, User
      can :manage, Profile
      can :manage, Configurable
      can :manage, Payment
      can :manage, Report
    else
      can [:change_password, :show], User
      can :manage, Post
      can :manage, Bid
      can :manage, Shipper
      can :manage, Notification
      can :manage, Profile
      can [:create], Report
      can :manage, Review
      can [:new, :create, :destroy], Payment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/configurable.rb
class Configurable < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
  
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  is_impressionable
  belongs_to :user
  has_many :bids, dependent: :delete_all
  has_one :shipper, dependent: :destroy

  validates :price, :presence => {:message => "Chưa có giá cho bài đăng"}
  validates :title, :presence => {:message => "Không được để trống"}
  validates :place_from, :presence => {:message => "Không được để trống"}
  validates :place_to, :presence => {:message => "Không được để trống"}
  validates :time_receive, :presence => {:message => "Không được để trống"}
  validates :time_send, :presence => {:message => "Không được để trống"}
  validate :check_time_recieve
  validate :check_time_send

  def self.search(from, to)
  # Title is for the above case, the OP incorrectly had 'name'
  if from.empty? == false && to.empty? == false
     where("place_from LIKE ?", "%#{from}%")
     where("place_to LIKE ?", "%#{to}%")
  elsif from.empty?
     where("place_to LIKE ?", "%#{to}%")
   else
     where("place_from LIKE ?", "%#{from}%")
   end
 end

 def check_time_recieve
   if self.time_receive > Time.now
     return true
   else
     errors.add(:time_receive, "Thời gian nhận không hợp lệ")
   end
 end

 def check_time_send
   if self.time_send > self.time_receive
     return true
   else
     errors.add(:time_send, "Thời gian giao phải lớn hơn thời gian nhận")
   end
 end

 class <<self
   def delete_post_deadline
     @posts = Post.all.where(status: false)
     @posts.each do |post|
       if post.time_receive < Time.now
         post.destroy
       end
     end
   end
 end


end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :name, :presence => {:message => "Không được để trống"}
  validates :date_of_birth, :presence => {:message => "Không được để trống"}
  validates :male, :presence => {:message => "Không được để trống"}
  validates :address, :presence => {:message => "Không được để trống"}
  validates :phone, :presence => {:message => "Không được để trống"},
                    :numericality => {only_integer: true, :message => "Không được chứa ký tự"},
                    :length => { is: 10 || 11, :message => "Phải là 10 hoặc 11 số" }
  validates :identity_card, :presence => {:message => "Không được để trống"},
                            :numericality => {only_integer: true, :message => "Không được chứa ký tự"},
                            :length => { is: 9 || 12, :message => "Phải là 9 hoặc 12 số" }
  validates :money, :presence => {:message => "Không được để trống"},
                    :numericality => {only_integer: true, :message => "Không được chứa ký tự"}

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/shipper.rb
class Shipper < ApplicationRecord
  belongs_to :user
  has_one :review
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :profile, dependent: :destroy
  has_many :notifications, dependent: :delete_all
  has_many :posts, dependent: :delete_all
  has_many :bids, dependent: :delete_all
  has_many :shippers, dependent: :delete_all
  has_many :reviews, through: :shippers
  has_many :reports
  has_many :payments


  def is_admin
    return true if self.role == 1
    return false
  end

  def locked?
    return true if self.lock == true
    return false
  end

  def has_profile
    return true if self.profile != nil
    return false
  end

  def sum_score
    sum = 0
    self.reviews.each do |review|
      sum += review.score
    end
    return sum
  end

  def confirmation_required?
    true
  end

  def self.search(email)
     where("email LIKE ?", "%#{email}%")
    #  where("place_to LIKE ?", "%#{to}%")
   end

  class <<self
    def unlock_user
      @users = User.where(lock: true)
      @users.each do |user|
        if (Time.now - user.date_lock)/1.day >= 30
          user.update(lock: false, date_lock: nil)
          UserMailer.send_mail_unlock(user).deliver_now
        end
      end
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :check_locked

  # skip_before_action :authenticate_profile, only: [:new, :create]
  Paperclip::Attachment.default_options[:default_url] = "/assets/user.png"
  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.create_profile profile_params
    if @profile.save
      flash[:success] = "Cập nhật thành công"
      redirect_to profile_path(@profile.id)
    else
      flash[:error] = "Cập nhật thất bại"
      render :new
    end
  end

  def show
    @profile = Profile.find_by id: params[:id]
  end

  def edit
    @profile = Profile.find_by id: params[:id]
  end

  def update
    @profile = Profile.find_by id: params[:id]
    if @profile.update profile_params
      flash[:success] = "Cập nhật thành công"
      redirect_to profile_path(@profile.id)
    else
      flash[:error] = "Cập nhật thất bại"
      render :edit
    end
  end

  private
  def profile_params
    profile_params = params.require(:profile).permit(:name, :date_of_birth, :male, :address, :phone, :identity_card, :avatar, :user_id)
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/warning_helper.rb
module WarningHelper
end

app/views/profiles/edit.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Người dùng
      <span class="glyphicon glyphicon-chevron-right"></span>
      Chỉnh sửa thông tin
    </div>
    <div class="col-md-4">
      <div class="add-post pull-right"><a href="<%= new_post_path %>">Đăng bài</a></div>
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-10 box col-sm-offset-1">
  <!-- <div class="title"><h3>Cập nhật thông tin</h3></div>
  <% if @profile.errors.any? %>
  <div class="col-md-4 alert-danger alert col-sm-offset-4">
  <% @profile.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </div>
  <% end %> -->
  <div class="col-md-5">
    <%= form_for @profile,url: profile_path(@profile),:html => { :multipart => true} do |f| %>
  <div class="form-group">
    <label>Họ tên *</label>
    <%= f.text_field :name, required: true, class: "form-control", placeholder: "Họ tên" %>
    <%= f.error_message_on :name %>
  </div>
  <div class="form-group date" >
    <label>Ngày sinh *</label>
    <%= f.text_field :date_of_birth,value: "#{f.object.date_of_birth.strftime("%d/%m/%Y")}", required: true, class: "form-control datepicker" ,id: "datepicker",  placeholder: "Ngày sinh" %>
    <%= f.error_message_on :date_of_birth %>
  </div>
  <div class="form-group">
    <label>Giới tính *</label>
    <%= f.select(:male, options_for_select([["Nam","Nam"], ["Nữ","Nữ"]], @profile.male),{},{class: "form-control"})%>
    <%= f.error_message_on :male %>
  </div>
  <div class="form-group">
    <label>Địa chỉ *</label>
    <%= f.text_field :address, required: true, class: "form-control", placeholder: "Địa chỉ" %>
    <%= f.error_message_on :address %>
  </div>

</div>

<div class="col-md-5 col-sm-offset-2">
  <div class="form-group">
    <label>Số điện thoại *</label>
    <%= f.text_field :phone, required: true, class: "form-control", placeholder: "Số điện thoại" %>
    <%= f.error_message_on :phone %>
  </div>
  <div class="form-group">
    <label>Số CMND *</label>
    <%= f.text_field :identity_card, required: true, class: "form-control", placeholder: "Số CMND" %>
    <%= f.error_message_on :identity_card %>
  </div>
  <div class="form-group">
    <div class="col-md-6">
      <label>Ảnh đại diện</label>
    <%= f.file_field :avatar, onchange: "readURL(this);"%>
    <%= f.error_message_on :avatar %>
    </div>
    <div class="col-md-4 pull-right" style="margin-top: 10px;">
      <img id="img_prev" src="#" alt="your image" />
    </div>

  </div>
  <div class="form-group" style="margin-top: 125px;">
    <button type="submit" class="btn btn-vip col-md-12">Cập nhật</button>
  </div>
</div>
<% end %>
  </div>
  <div class="col-md-10 box box-second col-sm-offset-1">
    <!-- <div class="title"><h3>Thay đổi mật khẩu</h3></div> -->
    <form action="<%= change_password_path %>" method="post">
    <div class="col-md-5">
    <div class="form-group">
      <label>Mật khẩu mới *</label>
      <input name="new_password" required  class= "form-control" placeholder= "Mật khẩu mới"/>
    </div>
    <div class="form-group">
      <label>Nhập lại mật khẩu mới *</label>
      <input name="renew_password" required  class= "form-control" placeholder= "Nhập lại mật khẩu mới"/>
    </div>
    </div>
    <div class="col-md-5 col-sm-offset-2">
    <div class="form-group">
      <label>Mật khẩu cũ *</label>
      <input name="old_password" required  class= "form-control" placeholder= "Mật khẩu cũ"/>
    </div>
    <div class="form-group" style="margin-top: 40px;">
      <button type="submit" class="btn btn-vip col-md-12">Thay đổi mật khẩu</button>
    </div>
  </div>
  </form>
  </div>
  </div>
</section>

app/views/profiles/new.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Người dùng
      <span class="glyphicon glyphicon-chevron-right"></span>
      Cập nhật thông tin
    </div>
    <div class="col-md-4">
      <div class="add-post pull-right"><a href="<%= new_post_path %>">Đăng bài</a></div>
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-10 box col-sm-offset-1">
  <div class="col-md-5">
    <%= form_for @profile,url: profiles_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <label>Họ tên *</label>
    <%= f.text_field :name, required: true, class: "form-control", placeholder: "Họ tên" %>
    <%= f.error_message_on :name %>
  </div>

  <div class="form-group">
    <label>Giới tính *</label>
    <%= f.select(:male, options_for_select([["Nam","Nam"], ["Nữ","Nữ"]]),{},{class: "form-control"})%>
    <%= f.error_message_on :male %>
  </div>
  <div class="form-group date" >
    <label>Ngày sinh *</label>
    <div class="input-group">
      <%= f.text_field :date_of_birth, required: true, class: "form-control datepicker" ,id: "datepicker",  placeholder: "Ngày sinh" %>
      <%= f.error_message_on :date_of_birth %>
      <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>
  <div class="form-group">
    <label>Địa chỉ *</label>
    <%= f.text_field :address, required: true, class: "form-control", placeholder: "Địa chỉ" %>
    <%= f.error_message_on :address %>
  </div>

</div>

<div class="col-md-5 col-sm-offset-2">
  <div class="form-group">
    <label>Số điện thoại *</label>
    <%= f.text_field :phone, required: true, class: "form-control", placeholder: "Số điện thoại" %>
    <%= f.error_message_on :phone %>
  </div>
  <div class="form-group">
    <label>Số CMND *</label>
    <%= f.text_field :identity_card, required: true, class: "form-control", placeholder: "Số CMND" %>
    <%= f.error_message_on :identity_card %>
  </div>
  <div class="form-group">
    <div class="col-md-6">
      <label>Ảnh đại diện</label>
    <%= f.file_field :avatar, onchange: "readURL(this);"%>
    <%= f.error_message_on :avatar %>
    </div>
    <div class="col-md-4 pull-right" style="margin-top: 10px;">
      <img id="img_prev" src="#" alt="your image" />
    </div>

  </div>
  <div class="form-group" style="margin-top: 125px;">
    <button type="submit" class="btn btn-vip col-md-12">Cập nhật</button>
  </div>
<% end %>
</div>
</div>
</div>
</section>

app/views/profiles/show.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Người dùng
      <span class="glyphicon glyphicon-chevron-right"></span>
      Thông tin cá nhân
    </div>
    <div class="col-md-4">
      <div class="add-post pull-right"><a href="<%= new_payment_path %>">Nạp tiền</a></div>
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="title-box">
  <h4>Thông tin người dùng</h4>
</div>
<div class="col-md-12">
<div class="col-md-12 box">
  <!-- <div class="title"><h3>Thông tin cá nhân</h3></div> -->
  <div class="col-md-5">
    <%= image_tag @profile.avatar.url(:medium) %>
  </div>
  <div class="col-md-7 show-profile">
    <table class="col-md-12">
    <tr>
      <th class="col-md-3">Họ tên</th>
      <td><%=@profile.name %></td>
    </tr>
    <tr>
      <th class="col-md-3">Giới tính</th>
      <td><%=@profile.male %></td>
    </tr>
    <tr>
      <th class="col-md-3">Ngày sinh</th>
      <td><%=@profile.date_of_birth.strftime("%d/%m/%Y") %></td>
    </tr>
    <tr>
      <th class="col-md-3">Địa chỉ</th>
      <td><%=@profile.address %></td>
    </tr>
    <tr>
      <th class="col-md-3">Số điện thoại</th>
      <td><%=@profile.phone %></td>
    </tr>
    <tr>
      <th class="col-md-3">Số CMND</th>
      <td><%=@profile.identity_card %></td>
    </tr>
    <tr>
      <th class="col-md-5">Điểm</th>
      <td><%= @profile.user.sum_score%></td>
    </tr>
    <tr>
      <th class="col-md-5">Tiền</th>
      <td><%= number_with_delimiter(@profile.money) + " vnđ"%></td>
    </tr>
  </table>
  </div>
  <div class="col-md-12">
      <div class="pull-right">
        <a href="<%= edit_profile_path(@profile.id) %>" class="btn btn-info">Chỉnh sửa</a>
      </div>
  </div>
</div>
</div>
<div class="title-box">
  <h4>Lịch sử thanh toán</h4>
</div>
<% @profile.user.payments.each do |payment| %>
<div class="col-md-6 payment-item" >
  <div class="user-bid" style="padding: 30px 10px;">
    <div class="col-md-10">
      <%= method_payment(payment) %> - <span class="gray-show"><%= payment.created_at.strftime("%d/%m/%Y")%></span>
    </div>
    <div class="col-md-2 ">
      <a href="javascript:;" class="red pull-right delete-payment" data-target="<%= payment.id %>">Xóa</a>
    </div>
    <p>
    <div class="col-md-12">
      Số tiền: <span class="blue-show"><%= number_with_delimiter(payment.money) %> vnđ</span>
    </div>
    </p>
  </div>
</div>
<% end %>

</div>
</section>