config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
    resources :profiles
    resources :users, only: [:index, :destroy, :show] do
      get 'details'
      get 'lock_user'
    end
    resources :payments
    post 'admin_payment' => 'payments#admin_payment'

    resources :notifications, only: [:index, :destroy]
    resources :configurable, only: [:edit, :update]
    post 'seen_notifications' => 'notifications#seen_notifications'
    post 'change_password' => 'users#change_password'
    post 'calculate_price' => 'posts#calculate_price'
    resources :bids
    resources :posts do
      get 'my_post_details'
    end
    get 'my_post_false' => 'posts#my_post_false'
    get 'my_post_true' => 'posts#my_post_true'
    get 'my_bid' => 'bids#my_bid'

    resources :shippers
    resources :reviews, only: [:index, :create]
    resources :reports, only: [:create, :destroy]
    resources :warning, only: :index


 root :to => 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :profile, dependent: :destroy
  has_many :notifications, dependent: :delete_all
  has_many :posts, dependent: :delete_all
  has_many :bids, dependent: :delete_all
  has_many :shippers, dependent: :delete_all
  has_many :reviews, through: :shippers
  has_many :reports
  has_many :payments


  def is_admin
    return true if self.role == 1
    return false
  end

  def locked?
    return true if self.lock == true
    return false
  end

  def has_profile
    return true if self.profile != nil
    return false
  end

  def sum_score
    sum = 0
    self.reviews.each do |review|
      sum += review.score
    end
    return sum
  end

  def confirmation_required?
    true
  end

  def self.search(email)
     where("email LIKE ?", "%#{email}%")
    #  where("place_to LIKE ?", "%#{to}%")
   end

  class <<self
    def unlock_user
      @users = User.where(lock: true)
      @users.each do |user|
        if (Time.now - user.date_lock)/1.day >= 30
          user.update(lock: false, date_lock: nil)
          UserMailer.send_mail_unlock(user).deliver_now
        end
      end
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      set_flash_message!(:notice, :confirmed)
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      flash[:notice] = "Email của bạn đã xác thực. Vui lòng đăng nhập"
      redirect_to root_path
    end
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    new_profile_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json
  # skip_before_action :authenticate_user
  # skip_before_action :authenticate_profile

  def create
    if params[:user][:password] == params[:user][:password_comfirmation]
        build_resource(sign_up_params)
        resource.save
        yield resource if block_given?
        if resource.persisted?
          # sign_up(resource_name, resource)
          return render :json => {:success => true,:message => 'Vui lòng xác thực email để quá trình đăng ký được hoàn tất.', :data => resource}
        else
          clean_up_passwords resource
          messages = resource.errors.messages
          return render :json => {:success => false, :message => 'Email đã tồn tại'}
        end
      else
        clean_up_passwords resource
        messages = "Mật khẩu không khớp"
        return render :json => {:success => false, :message => messages}
    end
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json

  def create
    resource = User.find_by_email params[:user][:email]
    if resource && resource.valid_password?(params[:user][:password])
      if resource.confirmed?
        sign_in(resource_name, resource)
        message = "Đăng nhập thành công"
        flash[:success] = "Đăng nhập thành công"

        # if resource.has_profile
          if resource.is_admin
            render :json => {:success => true, :login => true, :message => message, :confirmed => true, :admin => true }, status: 200
          else
            render :json => {:success => true, :login => true, :message => message, :confirmed => true, :admin => false }, status: 200
          end
        # else
        #   render :json => {:success => true, :login => true, :message => message, :confirmed => true }, status: 200
        # end
      else
        message = "Vui lòng xác thực email"
        render :json => {:success => true, :login => false, :message => message, :confirmed => false }
      end
    else
      message = "Email hoặc mật khẩu không đúng"
      return render :json => {:success => false, :login => false, :message => message}
    end
  end

 def signout
   sign_out(current_user)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     skip_before_action :verify_authenticity_token
     load_and_authorize_resource
     before_action :authenticate_user
     before_action :check_locked
     before_action :authenticate_profile
    def index
      @users = User.where(role: 0).search(params[:search]).order({ created_at: :desc }).paginate(:page => params[:page], :per_page => 20)
    end

    def show
      @user = User.find_by id: params[:id]
    end

    def destroy
      @user = User.find_by id: params[:id]
      if @user.destroy
        render :json => {:success => true}
      else
        render :json => {:success => false}
      end
    end

    def details
      @user = User.find_by id: params[:user_id]
    end

    def change_password
      @user = User.find_by id: current_user.id
      if @user.valid_password? params[:old_password]
        if params[:new_password] == params[:renew_password]
          if @user.update password: params[:new_password]
            flash[:success] = "Thay đổi thành công"
            sign_in @user, bypass: true
            redirect_to profile_path(@user.profile.id)
          else
            flash[:errors] = "Thay đổi thất bại"
            redirect_to edit_profile_path(@user.profile.id)
          end
        else
          flash[:errors] = "Mật khẩu không khớp"
          redirect_to edit_profile_path(@user.profile.id)
        end
      else
        flash[:errors] = "Mật khẩu cũ không đúng"
        redirect_to edit_profile_path(@user.profile.id)
      end
    end

    def lock_user
      @user = User.find_by id: params[:user_id]
      if @user.lock
        @user.update(lock: false, date_lock: nil)
        message = "Đã mở khóa người dùng"
        UserMailer.send_mail_unlock(@user).deliver_now
      else
        @user.update(lock: true, date_lock: Time.now)
        message = "Đã khóa người dùng"
        UserMailer.send_mail_lock(@user).deliver_now
      end
      locked = @user.lock
      render :json => {:success => true, :message => message, :locked => locked }
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/details.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Admin <span class="glyphicon glyphicon-chevron-right"></span> Thông tin người dùng
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="title-box">
  <h4>Thông tin người dùng</h4>
</div>

<div class="col-md-12 ">
  <div class="col-md-12 box">
  <div class="col-md-5">
    <%= image_tag @user.profile.avatar.url(:medium) %>
  </div>
  <div class="col-md-7 show-profile">
    <table class="col-md-12">
    <tr>
      <th class="col-md-4">Họ tên</th>
      <td><%= @user.profile.name %></td>
    </tr>
    <tr>
      <th class="col-md-4">Email</th>
      <td><%= @user.email%></td>
    </tr>
    <tr>
      <th class="col-md-4">Giới tính</th>
      <td><%= @user.profile.male %></td>
    </tr>
    <tr>
      <th class="col-md-4">Ngày sinh</th>
      <td><%= @user.profile.date_of_birth.strftime("%d/%m/%Y") %></td>
    </tr>
    <tr>
      <th class="col-md-5">Địa chỉ</th>
      <td><%= @user.profile.address %></td>
    </tr>
    <tr>
      <th class="col-md-5">Số điện thoại</th>
      <td><%= @user.profile.phone %></td>
    </tr>
    <tr>
      <th class="col-md-5">Số CMND</th>
      <td><%= @user.profile.identity_card %></td>
    </tr>
    <tr>
      <th class="col-md-5">Điểm</th>
      <td><%= @user.sum_score %></td>
    </tr>
    <!-- <tr>
      <th class="col-md-5">Tiền</th>
      <td><%= number_with_delimiter(@user.profile.money) %></td>
    </tr> -->
  </table>
  </div>
  <!-- <div class="col-md-4 col-sm-offset-5">
    <%= link_to "Back", :back, class: "btn btn-info col-md-6" %>
  </div> -->
</div>
</div>

<div class="title-box">
  <h4>Lịch sử thanh toán</h4>
</div>
<% @user.payments.each do |payment| %>
<div class="col-md-6 payment-item" >
  <div class="user-bid" style="padding: 30px 10px;">
    <div class="col-md-10">
      <%= method_payment(payment) %> - <span class="gray-show"><%= payment.created_at.strftime("%d/%m/%Y")%></span>
    </div>
    <div class="col-md-2 ">
      <a href="javascript:;" class="red pull-right delete-payment" data-target="<%= payment.id %>">Xóa</a>
    </div>
    <p>
    <div class="col-md-12">
      Số tiền: <span class="blue-show"><%= number_with_delimiter(payment.money) %> vnđ</span>
    </div>
    </p>
  </div>
</div>
<% end %>

<% if @user.reports.count > 0 %>
<div class="title-box">
<h4>Nội dung tố cáo</h4>
</div>

<% @user.reports.each do |report| %>
<div class="col-md-6 report-item">
  <div class="user-bid">
    <div class="col-md-10 report-comment">
      <%= report.comment %>
    </div>
    <div class="col-md-2 ">
      <a href="javascript:;" class="red pull-right delete-report" data-target="<%= report.id %>">Xóa</a>
    </div>
    <div class="col-md-12 gray-show">
      <%= report.created_at.strftime("%d/%m/%Y")%> - <%=User.find_by(id: report.user_report).profile.name %>
    </div>
  </div>
</div>
<% end %>
</div>
<% end %>
</div>
</section>

app/views/users/index.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-6">
      Admin
      <span class="glyphicon glyphicon-chevron-right"></span>
      Quản lý người dùng <span class="num-no1"><%= @users.count %> </span>
    </div>
    <div class="col-md-6">
      <div class="search__b clearfix pull-right">
        <form action="<%= users_path %>" method="get" remote="true">
        <div class="search_right">
          <!-- <%= hidden_field_tag :authenticity_token, form_authenticity_token %> -->
          <!-- <input type="text" class="input-search" name="search[place_from]" placeholder="Điểm đi"> -->
          <input type="text" class="input-search" name="search" placeholder="Email">
          <span class="searchbtn">
            <button class="btn-search" type="submit"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </form>
        </div>
      </div>
      </div>
  </div>
</div>
<section class="main-body">
<div class="col-md-12 box">
  <!-- <div class="title"><h3>Quản lý người dùng</h3></div> -->
  <div class="col-md-12">
  <table class="table table-striped table-bordered">
    <tr>
      <th>STT</th>
      <th>Email</th>
      <th>Họ tên</th>
      <th>Điểm</th>
      <th>Tiền</th>
      <th>Ngày tạo</th>
      <th>Bị tố cáo</th>
      <th>Ngày khóa</th>
      <th>Chức năng</th>
    </tr>
    <% @users.each_with_index do |user, index| %>
    <tr class="box-user">
      <td><%= index+1 %></td>
      <td><%= user.email %></td>
      <td><%= user.profile.try(:name) %></td>
      <td><%= user.sum_score%></td>
      <td><%= number_with_delimiter(user.profile.try(:money)) %></td>
      <td><%= user.created_at.strftime("%d/%m/%Y") %></td>
      <td><a href="<%= reports_path %>"><%= user.reports.count %></a></td>
      <td><% if user.date_lock %><%= user.date_lock.strftime("%d/%m/%Y") %> <% end %></td>
      <td>
        <a data-target="<%= user.id %>" class="btn btn-danger delete-user">
          <span class="glyphicon glyphicon-remove-sign"></span>
          Xóa</a>
        <a data-target="<%= user.id %>" class="btn btn-primary lock-user">
          <!-- <span class="glyphicon glyphicon-lock"></span> -->
          <%= user.try(:lock) ? +'<i class="fa fa-unlock"></i>'.html_safe+" Mở khóa" : +'<i class="fa fa-lock"></i>'.html_safe+" Khóa"    %></a>
        <% if user.profile %>
        <a type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal<%= user.id %>">
          <span class="glyphicon glyphicon-usd"></span>
          Nạp tiền</a>
        <a href="<%= user_details_path(user.id) %>" class="btn btn-info">
          <span class="glyphicon glyphicon-folder-open"></span>
          Thông tin</a>


        <div id="myModal<%= user.id %>" class="modal fade modal-payment myModal" role="dialog">
          <div class="modal-dialog modal-edit">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                <div class="form-box-inner" id="payment">
                  <div class="row">
                    <h3 class="modal-title text-center">Nạp tiền</h3>
                    <div class="form-container col-xs-12 col-md-12 message-payment">
                      <form class="login-form" data-toggle="validator">
                        <input type="text" class="user_id" value="<%= user.id %>" hidden="hidden">
                        <div class="form-group password">
                          <input id="money" type="number" pattern="(\d{3})([\.])(\d{2})" class="form-control login-password money">
                        </div>
                        <button type="button" class="btn-main btn-login btn-payment">Nạp tiền</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
        <%end %>

      </td>
    </tr>

    <% end %>
  </table>
  <div class="pull-right">
    <%= will_paginate @posts %>
  </div>
  </div>
</div>
</section>

app/views/users/show.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Thông tin người dùng
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-12 box">
  <!-- <div class="title"><h3>Thông tin cá nhân</h3></div> -->
  <div class="col-md-5">
    <%= image_tag @user.profile.avatar.url(:medium) %>
  </div>
  <div class="col-md-7 show-profile">
    <table class="col-md-12">
    <tr>
      <th class="col-md-4">Họ tên</th>
      <td><%= @user.profile.name %></td>
    </tr>
    <tr>
      <th class="col-md-4">Email</th>
      <td><%= @user.email%></td>
    </tr>
    <tr>
      <th class="col-md-4">Giới tính</th>
      <td><%= @user.profile.male %></td>
    </tr>
    <tr>
      <th class="col-md-4">Ngày sinh</th>
      <td><%= @user.profile.date_of_birth.strftime("%d/%m/%Y") %></td>
    </tr>
    <tr>
      <th class="col-md-5">Địa chỉ</th>
      <td><%= @user.profile.address %></td>
    </tr>
    <tr>
      <th class="col-md-5">Số điện thoại</th>
      <td><%= @user.profile.phone %></td>
    </tr>
    <tr>
      <th class="col-md-5">Số CMND</th>
      <td><%= @user.profile.identity_card %></td>
    </tr>
    <tr>
      <th class="col-md-5">Điểm</th>
      <td><%= @user.sum_score %></td>
    </tr>
    <!-- <tr>
      <th class="col-md-5">Tiền</th>
      <td><%= number_with_delimiter(@user.profile.money) %></td>
    </tr> -->
  </table>
  </div>
  <div class="col-md-4 col-sm-offset-5">
    <%= link_to "Back", :back, class: "btn btn-info col-md-6" %>
  </div>
</div>
<div class="modal"></div>
</div>
</section>