config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
    resources :profiles
    resources :users, only: [:index, :destroy, :show] do
      get 'details'
      get 'lock_user'
    end
    resources :payments
    post 'admin_payment' => 'payments#admin_payment'

    resources :notifications, only: [:index, :destroy]
    resources :configurable, only: [:edit, :update]
    post 'seen_notifications' => 'notifications#seen_notifications'
    post 'change_password' => 'users#change_password'
    post 'calculate_price' => 'posts#calculate_price'
    resources :bids
    resources :posts do
      get 'my_post_details'
    end
    get 'my_post_false' => 'posts#my_post_false'
    get 'my_post_true' => 'posts#my_post_true'
    get 'my_bid' => 'bids#my_bid'

    resources :shippers
    resources :reviews, only: [:index, :create]
    resources :reports, only: [:create, :destroy]
    resources :warning, only: :index


 root :to => 'home#index'
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # load_and_authorize_resource
  before_action :authenticate_user
  before_action :check_locked
  before_action :authenticate_profile

  def admin_payment
    @user = User.find_by id: params[:payment][:user_id].to_i
    if params[:payment][:money].to_i >= Configurable.first.money_payment
        @payment = Payment.new(payment_params.merge(card_token: "Admin"))
        if @payment.save
          money_payment = params[:payment][:money].to_i
          total_money = @user.profile.money + money_payment
          @user.profile.update money: total_money
          @user.notifications.create(send_id: current_user.id, content: "Tài khoản của bạn vừa được cộng thêm #{money_payment} vnđ")
          flash[:success] = "Nạp tiền thành công"
          message = "Nạp tiền thành công"
          render :json => {success: true, message: message}
        else
          message = "Nạp tiền thất bại"
          render :json => {success: false, message: message}
        end
      else
        message = "Số tiền phải từ #{Configurable.first.money_payment} trở lên"
        render :json => {success: false, message: message}
      end

  end

  # def new
  #   @ayment = Payment.new
  # end
    def new
    end

    def create
      @configurable = Configurable.first
      @customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: @customer.id,
        amount: @configurable.money_payment,
        description: 'Rails Stripe customer',
        currency: 'vnd'
      )

      if charge
        @user = current_user
        @payment = Payment.create(money: @configurable.money_payment, user_id: @user.id, card_token: @customer.sources.data[0]["id"])
        total_money = @user.profile.money + @configurable.money_payment
        @user.profile.update money: total_money
        @user.notifications.create(send_id: User.first.id, content: "Tài khoản của bạn vừa được cộng thêm #{@configurable.money_payment} vnđ")
        UserMailer.send_mail_payment(@user).deliver_now
        flash[:success] = "Nạp tiền thành công"
        redirect_to new_payment_path
      else
        flash[:error] = Stripe::CardError.message
        redirect_to new_payment_path
      end
    end

    def destroy
      @payment = Report.find_by id: params[:id]
      if @payment.destroy
        render :json => {:success => true, :message => "Xóa thành công"}
      else
        render :json => {:success => false, :message => "Xóa thất bại"}
      end
    end

    def payment_params
      params.require(:payment).permit(:money, :user_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Người dùng <span class="glyphicon glyphicon-chevron-right"></span> Phương thức thanh toán
    </div>
    <div class="col-md-4">
      <div class="pull-right">
        Số dư: <span class="num-no1">
          <% if current_user.profile %>
            <%= number_with_delimiter(current_user.profile.money) %>
          <% else %>
            0
            <% end %>
          </span><span> vnđ</span>
      </div>
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-12">
  <div class="col-md-6">
    <div class="box">
      <div class="title">
        <h4>Thanh toán trực tiếp</h4>
      </div>
      <p class="payment-row">Số tiền tối thiểu cho mỗi lần thanh toán là <%= number_with_delimiter(Configurable.first.money_payment) %> vnđ</p>
      <p class="payment-row">Bạn vui lòng đến văn phòng của chúng tôi để thanh toán trực tiếp </p>
    </div>
  </div>
  <div class="col-md-6">
    <div class="box">
      <div class="title">
        <h4>Thanh toán qua thẻ</h4>
      </div>
      <p class="payment-row">Số tiền thanh toán là <%= number_with_delimiter(Configurable.first.money_payment) %> vnđ</p>
      <div class="stripe-button-container">
      <%= form_tag payments_path, class: "payment-form" do %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" value="Thanh toán" hidden="true"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Vui lòng nhập thông tin"
                data-name="Shipper"

                data-amount="<%= Configurable.first.money_payment %>"
                data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                data-notrack
                data-currency="vnd"
                data-locale="auto"></script>
                <!-- <button type="submit" class="stripe-button-el" style="visibility: visible;">
                  <span style="display: block; min-height: 30px;">Thanh toán</span>
                </button> -->
      <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</section>