config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
    resources :profiles
    resources :users, only: [:index, :destroy, :show] do
      get 'details'
      get 'lock_user'
    end
    resources :payments
    post 'admin_payment' => 'payments#admin_payment'

    resources :notifications, only: [:index, :destroy]
    resources :configurable, only: [:edit, :update]
    post 'seen_notifications' => 'notifications#seen_notifications'
    post 'change_password' => 'users#change_password'
    post 'calculate_price' => 'posts#calculate_price'
    resources :bids
    resources :posts do
      get 'my_post_details'
    end
    get 'my_post_false' => 'posts#my_post_false'
    get 'my_post_true' => 'posts#my_post_true'
    get 'my_bid' => 'bids#my_bid'

    resources :shippers
    resources :reviews, only: [:index, :create]
    resources :reports, only: [:create, :destroy]
    resources :warning, only: :index


 root :to => 'home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  is_impressionable
  belongs_to :user
  has_many :bids, dependent: :delete_all
  has_one :shipper, dependent: :destroy

  validates :price, :presence => {:message => "Chưa có giá cho bài đăng"}
  validates :title, :presence => {:message => "Không được để trống"}
  validates :place_from, :presence => {:message => "Không được để trống"}
  validates :place_to, :presence => {:message => "Không được để trống"}
  validates :time_receive, :presence => {:message => "Không được để trống"}
  validates :time_send, :presence => {:message => "Không được để trống"}
  validate :check_time_recieve
  validate :check_time_send

  def self.search(from, to)
  # Title is for the above case, the OP incorrectly had 'name'
  if from.empty? == false && to.empty? == false
     where("place_from LIKE ?", "%#{from}%")
     where("place_to LIKE ?", "%#{to}%")
  elsif from.empty?
     where("place_to LIKE ?", "%#{to}%")
   else
     where("place_from LIKE ?", "%#{from}%")
   end
 end

 def check_time_recieve
   if self.time_receive > Time.now
     return true
   else
     errors.add(:time_receive, "Thời gian nhận không hợp lệ")
   end
 end

 def check_time_send
   if self.time_send > self.time_receive
     return true
   else
     errors.add(:time_send, "Thời gian giao phải lớn hơn thời gian nhận")
   end
 end

 class <<self
   def delete_post_deadline
     @posts = Post.all.where(status: false)
     @posts.each do |post|
       if post.time_receive < Time.now
         post.destroy
       end
     end
   end
 end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user
  before_action :check_locked
  before_action :authenticate_profile
  impressionist :actions=>[:show]
  before_action :set_post, only: [:edit, :update, :destroy, :show]
  def index
    # @posts = Post.where(status: false).order({ created_at: :desc })
    if params[:search]
      @posts = Post.where(status: false).search(params[:search][:place_from], params[:search][:place_to]).order({ created_at: :desc }).paginate(:page => params[:page], :per_page => 10)
    else
      @posts = Post.where(status: false).order({ created_at: :desc }).paginate(:page => params[:page], :per_page => 10)
    end
  end

  def new
    @post = Post.new
  end

  def calculate_price
    @configurable = Configurable.first
    distance = (params[:distance].to_f/1000+0.5).to_i

    if distance <= 3
      price = @configurable.price_near
    else
      price = @configurable.price_near + @configurable.price_away*(distance - 3)
    end
    render :json => {:success => true, :data => {:price => price, :distance => distance}}
  end

  def create
    @post = current_user.posts.new post_params
    if @post.save
      flash[:success] = "Thêm mới thành công"
      redirect_to my_post_false_path
    else
      flash[:errors] = "Thêm mới thất bại"
      render :new
    end
  end

  def show
    impressionist(@post)
  end

  def edit
  end

  def update
    if @post.update post_params
      flash[:success] = "Cập nhật thành công"
      redirect_to my_post_false_path
    else
      flash[:errors] = "Cập nhật thất bại"
      render :edit
    end
  end

  def destroy
    if @post.destroy
      counter_post = current_user.posts.count
      render :json => {:success => true, :message => "Xóa thành công", :counter_post => counter_post}
    else
      render :json => {:success => false, :message => "Xóa thất bại"}
    end
  end

  def my_post_false
    @posts = current_user.posts.where(status: false).order({ created_at: :desc })
  end

  def my_post_true
    @posts = current_user.posts.where(status: true).order({ created_at: :desc })
  end

  def my_post_details
    @post = Post.find_by id: params[:post_id]
  end


  private

  def set_post
    @post = Post.find_by id: params[:id]
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :content, :place_from, :place_to, :time_receive, :time_send, :price, :status)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-4">
      <div class="add-post"><a href="<%= new_post_path %>">Đăng bài</a></div>
    </div>
    <div class="col-md-8">
      <div class="search__b clearfix pull-right">
        <form action="<%= posts_path %>" method="get">
        <div class="search_right">
          <!-- <%= hidden_field_tag :authenticity_token, form_authenticity_token %> -->
          <input type="text" class="input-search" name="search[place_from]" placeholder="Điểm đi">
          <input type="text" class="input-search" name="search[place_to]" placeholder="Điểm đến">
          <span class="searchbtn">
            <button class="btn-search" type="submit"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </form>
        </div>
      </div>
      </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-12">
  <% @posts.each do |post| %>
    <div class="col-md-12 post-item">
      <div class="col-md-12">
        <div class="col-md-9">
          <div class="col-md-12">
            <h4><a href="<%= post_path(post.id) %>"><%= post.title %></a></h4>
            <span><%= post.content %></span>
          </div>

        </div>
        <div class="col-md-3 nav">
          <div class="col-md-9 date-post">
            <%= time_ago_converter time_ago_in_words(post.created_at)+ " trước"%>
          </div>
          <div class="col-md-3">
            <li class="dropdown pull-right">
               <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
               <ul class="dropdown-menu">
                 <li><a href="<%= post_path(post.id)%>">Chi tiết</a></li>
                 <li><a href="" data-toggle="modal" data-target="#myModal<%= post.id %>">Đấu giá</a></li>
               </ul>
             </li>
          </div>

        </div>
      </div>
      <div class="col-md-12 top-20">
        <div class="col-md-8">
          <table class="col-md-12">
            <tr>
              <th class="col-md-8">Điểm đi</th>
              <th class="col-md-4">Thời gian đi</th>
            </tr>
            <tr>
              <td class="col-md-8"><%= post.place_from %></td>
              <td class="col-md-4"><%= post.time_receive.strftime("%d/%m/%Y %R") %></td>
            </tr>
            <tr>
              <th class="col-md-8">Điểm đến</th>
              <th class="col-md-4">Thời gian đến</th>
            </tr>
            <tr>
              <td class="col-md-8"><%= post.place_to%></td>
              <td class="col-md-4"><%= post.time_send.strftime("%d/%m/%Y %R") %></td>
            </tr>
          </table>
        </div>
        <div class="col-md-4">
          <div class="box-price">
            <p>Lượt xem</p>
            <p><%= post.impressionist_count %></p>
          </div>
          <div class="box-price">
            <p>Đấu giá</p>
            <p><%= post.bids.count %></p>
          </div>
          <div class="box-price">
            <p>Giá</p>
            <p><%= number_with_delimiter(post.price) %> vnđ</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 pull-right">
        <div class="col-md-12">
          <div class="pull-right own-post">
            Người đăng: <%= post.user.profile.name %>
          </div>
        </div>
      </div>
    </div>
    <div id="myModal<%= post.id %>" class="modal fade modal-bid" role="dialog">
      <div class="modal-dialog modal-login">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="form-box-inner">
              <h3 class="title text-center">Đấu giá</h3>
              <div class="row">
                <div class="form-container col-xs-12 col-md-12 message-bid">
                  <form class="login-form" data-toggle="validator">
                    <input class="post_id" value="<%= post.id %>" hidden="true">
                    <div class="form-group">
                      <label >Giá đề xuất </label>
                      <input type="number" class="form-control login-email bid_price" placeholder="Giá đề xuất" name="pid_price" required>
                    </div>
                    <a type="button" href="javascript:;" class="btn-main btn-login btn_bid" id="btn_bid">Đấu giá</a>

                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  <% end %>
  <div class="pull-right">
    <%= will_paginate @posts %>
  </div>
</div>
</div>
</section>

app/views/posts/my_bid.html.erb
<section class="main-body">
<div class="container">
<div class="col-md-12">
  <div class="menu-post">
    <ul class="nav nav-tabs">
      <li role="presentation"><a href="<%= posts_path %>">Bài đăng</a></li>
      <li role="presentation"><a href="<%= my_post_path %>">Bài đăng của tôi</a></li>
      <li role="presentation" class="active"><a href="<%= my_bid_path %>">Đã đấu giá</a></li>
    </ul>
  </div>
  <% if @bids.empty? %>
    <div class="col-md-4 alert alert-danger no-post col-sm-offset-4">
    <div>Bạn không có đấu giá nào</div>
    <div class="top-20"><a href="<%= posts_path %>" class="btn btn-vip">Bài đăng</a></div>
    </div>
  <% else %>
  <% @bids.each do |bid| %>
    <div class="col-md-12 post-item">
      <div class="col-md-12">
        <div class="col-md-10">
          <div class="col-md-12">
            <h4><a href="<%= post_path(bid.post.id) %>"><%= bid.post.title %></a></h4>
            <span><%= bid.post.content %></span>
          </div>

        </div>
        <div class="col-md-2 nav">
          <div class="col-md-9 date-post">
            <%= time_ago_converter time_ago_in_words(bid.post.created_at)+" trước" %>
          </div>
          <div class="col-md-3">
            <li class="dropdown pull-right">
               <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
               <ul class="dropdown-menu">
                 <li><a href="<%= post_path(bid.post.id)%>">Chi tiết</a></li>
                 <li><a href="" data-toggle="modal" data-target="#myModal<%= bid.post.id %>">Đấu giá</a></li>
               </ul>
             </li>
          </div>

        </div>
      </div>
      <div class="col-md-12 top-20">
        <div class="col-md-7">
          <table class="col-md-12">
            <tr>
              <th class="col-md-8">Điểm đi</th>
              <th class="col-md-4">Thời gian đi</th>
            </tr>
            <tr>
              <td class="col-md-8"><%= bid.post.place_from %></td>
              <td class="col-md-4"><%= bid.post.time_receive.strftime("%d/%m/%Y %R") %></td>
            </tr>
            <tr>
              <th class="col-md-8">Điểm đến</th>
              <th class="col-md-4">Thời gian đến</th>
            </tr>
            <tr>
              <td class="col-md-8"><%= bid.post.place_to%></td>
              <td class="col-md-4"><%= bid.post.time_send.strftime("%d/%m/%Y %R") %></td>
            </tr>
          </table>
        </div>
        <div class="col-md-5">
          <div class="box-price">
            <p>Lượt xem</p>
            <p><%= bid.post.impressionist_count %></p>
          </div>
          <div class="box-price">
            <p>Đấu giá</p>
            <p><%= bid.post.bids.count %></p>
          </div>
          <div class="box-price">
            <p>Giá đấu</p>
            <p><%= number_with_delimiter(bid.bid_price) %></p>
          </div>
          <div class="box-price">
            <p>Giá</p>
            <p><%= number_with_delimiter(bid.post.price) %></p>
          </div>
        </div>
      </div>
    </div>
    <div id="myModal<%= bid.post.id %>" class="modal fade modal-bid" role="dialog">
      <div class="modal-dialog modal-login">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="form-box-inner">
              <h2 class="title text-center">Đấu giá</h2>
              <div class="row">
                <div class="form-container col-xs-12 col-md-12 message-bid">
                  <form class="login-form" data-toggle="validator">
                    <input class="post_id" value="<%= bid.post.id %>" hidden="true">
                    <div class="form-group">
                      <label >Giá đề xuất </label>
                      <input type="number" class="form-control login-email bid_price" placeholder="Giá đề xuất" name="pid_price" required>
                    </div>
                    <div class="form-group password">
                      <label >Nội dung</label>
                      <textarea  rows="4" class="form-control login-email bid_comment" name="pid_comment"></textarea>

                    </div>
                    <a type="button" href="javascript:;" class="btn-main btn-login" id="btn_bid">Hủy đấu giá</a>

                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  <% end %>
  <% end %>
</div>
</div>
</section>

app/views/posts/my_post_details.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Bài đăng của tôi
      <span class="glyphicon glyphicon-chevron-right"></span>
      Tìm shipper
      <span class="glyphicon glyphicon-chevron-right"></span>
      Người đấu giá
    </div>
    <div class="col-md-4">
      <div class="add-post pull-right"><a href="<%= new_post_path %>">Đăng bài</a></div>
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-12">
  <% if @post.bids.empty? %>
      <div class="col-md-4 alert alert-danger no-post col-sm-offset-4">
      <div>Không có đấu giá nào</div>
      </div>
  <% else %>
  <div class="post_empty">
  </div>
  <%  @post.bids.each do |bid| %>
    <div class="col-md-6 box-user-bid">
      <div class="user-bid">
        <div class="col-md-3 bid-avatar">
          <span><img src="<%= bid.user.profile.avatar.url(:thumb) %>" /></span>
        </div>
        <div class="col-md-7 bid-info">
          <div class="col-md-12">
            <span><a href="#" class="blue01"><%= bid.user.profile.name %></a></span>
          </div>
          <div class="bid-score">
            <span><%= bid.user.sum_score %> điểm</span>
          </div>
          <div class="bid-score">
            <span><%= number_with_delimiter(bid.bid_price) %> vnđ</span>
          </div>
        </div>
        <div class="col-md-2 bid-action ">
          <a href="javascript:;" class="pull-right choose-shipper" data-target="<%= bid.id %>">Chọn</a>
          <a href="javascript:;" class="red pull-right delete-bid" data-target="<%= bid.id %>">Xóa</a>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>
</div>
</section>

app/views/posts/my_post_false.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Bài đăng của tôi <span class="glyphicon glyphicon-chevron-right"></span> Tìm shipper
    </div>
    <div class="col-md-4">
      <div class="add-post pull-right"><a href="<%= new_post_path %>">Đăng bài</a></div>
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-12">
  <% if @posts.empty? %>
      <div class="col-md-4 alert alert-danger no-post col-sm-offset-4">
      <div>Bạn không có bài đăng nào</div>
      </div>
  <% else %>
  <div class="post_empty">
  </div>
  <%  @posts.each do |post| %>
    <div class="col-md-12 post-item">
      <div class="col-md-12">
        <div class="col-md-10">
          <div class="col-md-12">
            <h4><a href="<%= post_path(post.id) %>"><%= post.title %></a></h4>
            <span><%= post.content %></span>
          </div>

        </div>
        <div class="col-md-2 nav">
          <div class="col-md-9 date-post">
            <%= time_ago_converter time_ago_in_words(post.created_at)+" trước" %>
          </div>
          <div class="col-md-3">
            <li class="dropdown pull-right">
               <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
               <ul class="dropdown-menu">
                 <li><a href="<%= post_path(post.id)%>">Chi tiết</a></li>
                 <% if post.bids.count < 1 %>
                 <li><a href="<%= edit_post_path(post.id)%>">Chỉnh sửa</a></li>
                 <% end %>
                 <li><a href="<%= post_my_post_details_path(post) %>">Người đấu giá</a></li>
                 <li><a href="javascript:;"  class="red delete-post" data-toggle="modal" data-target="<%= post.id %>">Xóa</a></li>
               </ul>
             </li>
          </div>

        </div>
      </div>
      <div class="col-md-12 top-20">
        <div class="col-md-8">
          <table class="col-md-12">
            <tr>
              <th class="col-md-8">Điểm đi</th>
              <th class="col-md-4">Thời gian đi</th>
            </tr>
            <tr>
              <td class="col-md-8"><%= post.place_from %></td>
              <td class="col-md-4"><%= post.time_receive.strftime("%d/%m/%Y %R") %></td>
            </tr>
            <tr>
              <th class="col-md-8">Điểm đến</th>
              <th class="col-md-4">Thời gian đến</th>
            </tr>
            <tr>
              <td class="col-md-8"><%= post.place_to%></td>
              <td class="col-md-4"><%= post.time_send.strftime("%d/%m/%Y %R") %></td>
            </tr>
          </table>
        </div>
        <div class="col-md-4">
          <div class="box-price">
            <p>Lượt xem</p>
            <p><%= post.impressionist_count %></p>
          </div>
          <div class="box-price">
            <p>Đấu giá</p>
            <p><%= post.bids.count %></p>
          </div>
          <div class="box-price">
            <p>Giá</p>
            <p><%= number_with_delimiter(post.price) %> vnđ</p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>
</div>
</section>

app/views/posts/my_post_true.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Bài đăng của tôi <span class="glyphicon glyphicon-chevron-right"></span> Đã có shipper
    </div>
    <div class="col-md-4">
      <div class="add-post pull-right"><a href="<%= new_post_path %>">Đăng bài</a></div>
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-12">
  <% if @posts.empty? %>
      <div class="col-md-4 alert alert-danger no-post col-sm-offset-4">
      <div>Bạn không có bài đăng nào</div>
      <!-- <div class="top-20"><a href="<%= new_post_path %>" class="btn btn-vip">Đăng bài</a></div> -->
      </div>
  <% else %>
  <div class="post_empty">
  </div>
  <%  @posts.each do |post| %>
    <div class="col-md-12 post-item">
      <div class="col-md-12">
        <div class="col-md-10">
          <div class="col-md-12">
            <h4><a href="<%= post_path(post.id) %>"><%= post.title %></a></h4>
            <span><%= post.content %></span>
          </div>

        </div>
        <div class="col-md-2 nav">
          <div class="col-md-9 date-post">
            <%= time_ago_converter time_ago_in_words(post.created_at)+" trước" %>
          </div>
          <div class="col-md-3">
            <li class="dropdown pull-right">
               <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
               <ul class="dropdown-menu">
                 <li><a href="<%= post_path(post.id)%>">Chi tiết</a></li>
                 <!-- <li><a href="<%= post_my_post_details_path(post) %>" class="orange">Người đấu giá</a></li> -->
                 <li><a href="javascript:;"  class="red delete-post" data-target="<%= post.id %>">Xóa</a></li>
               </ul>
             </li>
          </div>

        </div>
      </div>
      <div class="col-md-12 top-20">
        <div class="col-md-8">
          <table class="col-md-12">
            <tr>
              <th class="col-md-8">Điểm đi</th>
              <th class="col-md-4">Thời gian đi</th>
            </tr>
            <tr>
              <td class="col-md-8"><%= post.place_from %></td>
              <td class="col-md-4"><%= post.time_receive.strftime("%d/%m/%Y %R") %></td>
            </tr>
            <tr>
              <th class="col-md-8">Điểm đến</th>
              <th class="col-md-4">Thời gian đến</th>
            </tr>
            <tr>
              <td class="col-md-8"><%= post.place_to%></td>
              <td class="col-md-4"><%= post.time_send.strftime("%d/%m/%Y %R") %></td>
            </tr>
          </table>
        </div>
        <div class="col-md-4 ">
          <div class="col-md-5 btm-10"><b>Người ship:</b></div>
          <div class="col-md-7 btm-10"><a href="<%= user_path(post.shipper.user.id) %>" class="blue02"><%= post.shipper.user.profile.name %></a></div>
          <div class="col-md-5 btm-10"><b>Giá:</b></div>
          <div class="col-md-7 btm-10"><span><%= number_with_delimiter(post.shipper.money_ship, precision: 0) %> vnđ</span></div>
          <% if post.shipper.review %>
            <div class="col-md-5 btm-10"><b>Đánh giá:</b></div>
            <div class=" col-md-7 btm-10">
              <div class="star-rated" data-score="<%= post.shipper.review.score%>"></div>
            </div>
            <div class="col-md-5 btm-10"><b>Nhận xét:</b></div>
            <div class="col-md-7 btm-10"><%= post.shipper.review.comment%></div>
          <% else %>
            <div class="reviews">
              <form>
              <div class="reviews-content">
                <div class="col-md-5 btm-10"><b>Đánh giá:</b></div>
                <div class="reviews col-md-7 btm-10">
                  <div class="star-rating"></div>
                </div>
                <input type="text" hidden class="shipper_id" value="<%= post.shipper.id %>">
                <div class="col-md-12 btm-10"><textarea name="review[comment]" cols="30" rows="3" class="comment"></textarea></div>
                <div class="col-md-12 btm-10"><button type="button" class="btn btn-vip pull-right review" data-target="<%= post.shipper.id%>">Đánh giá</button></div>
              </form>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>
</div>
</section>
<script>
$('.star-rating').raty({
  path: "/assets",
  scoreName: "review[score]"
});
  $('.star-rated').raty({
    path: "/assets",
    scoreName: "review[score]",
    readOnly: true,
    score: function() {
      return $(this).attr("data-score");
    }
  });
</script>

app/views/posts/show.html.erb
<div class="support-menu fixed-top">
  <div class="container">
    <div class="col-md-8">
      Chi tiết bài đăng <span class="glyphicon glyphicon-chevron-right"></span> <%= @post.title %>
    </div>
    <div class="col-md-4">
      <div class="add-post pull-right"><a href="<%= new_post_path %>">Đăng bài</a></div>
    </div>
  </div>
</div>
<section class="main-body">
<div class="container">
<div class="col-md-12 box border-botttom-gray">
    <div class="col-md-12">
      <div class="col-md-10 border-botttom-gray">
        <h4 class="blue-show"><%= @post.title %></h4>
      </div>
      <div class="col-md-2 border-botttom-gray ">
      <h4 class="blue-show pull-right"> <%=   number_with_delimiter(@post.price) %> vnđ</h4>
      </div>
      <div class="col-md-12">
        <span class="gray-show"><%= @post.content %></span>
      </div>
    </div>
    <div class="col-md-12 top-20">
        <div class="col-md-2 gray-show">Điểm đi:</div>
        <div class="col-md-6 blue-show"><%= @post.place_from %></div>
        <div class="col-md-2 gray-show">Thời gian nhận:</div>
        <div class="col-md-2 blue-show"><%= @post.time_receive.strftime("%d/%m/%Y %R") %></div>

        <div class="col-md-2 gray-show">Điểm đến:</div>
        <div class="col-md-6 blue-show"><%= @post.place_to%></div>
        <div class="col-md-2 gray-show">Thời gian giao:</div>
        <div class="col-md-2 blue-show"><%= @post.time_send.strftime("%d/%m/%Y %R") %></div>
  </div>
</div>
<div class="col-md-12 post-item border-botttom-gray">
  <div class="col-md-6" id="dvMap" style="height: 500px;" onload="initialize();"></div>
  <div class="col-md-6" id="dvPanel" style="height: 500px; overflow: auto;"></div>
</div>
</div>
</section>
<script type="text/javascript">
function initMap() {
     var origin = "<%= @post.place_from %>";
     var destination = "<%= @post.place_to %>";
     var directionsDisplay;
      directionsDisplay = new google.maps.DirectionsRenderer();
      map = new google.maps.Map(document.getElementById('dvMap'));
      directionsDisplay.setMap(map);
      directionsDisplay.setPanel(document.getElementById('dvPanel'));
       var request = {
           origin: origin,
           destination: destination,
           optimizeWaypoints: false,
           travelMode: google.maps.TravelMode.DRIVING,
           provideRouteAlternatives: true

       };
       var directionsService = new google.maps.DirectionsService();
       directionsService.route(request, function (response, status) {
           if (status == google.maps.DirectionsStatus.OK) {
               directionsDisplay.setDirections(response);
           }
       });

}
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAw_byJaxgnV2ZAhS8cF8OOSdV2UGA2mkA&language=vi&callback=initMap"></script></script>